<?php

namespace Mdespeuilles\RedirectBundle\Repository;

/**
 * NotFoundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotFoundRepository extends \Doctrine\ORM\EntityRepository
{
}
